/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['DM Serif Display', 'Georgia', 'serif'],
      },
      colors: {
        baby: {
          pink: '#FFE4EC',
          'pink-deep': '#FFB8D0',
          'pink-soft': '#FFF0F5',
          rose: '#FF7EB3',
          lavender: '#E8DAF5',
          'lavender-deep': '#C9A9E4',
          mint: '#D4F5E9',
          'mint-deep': '#7DD3B0',
          sky: '#D6EEFF',
          'sky-deep': '#7DBFEF',
          peach: '#FFE5D4',
          'peach-deep': '#FFB899',
          cream: '#FFF9F0',
          yellow: '#FFF3CC',
          'yellow-deep': '#FFD966',
        },
        brand: {
          50: '#FFF5F7',
          100: '#FFE0E8',
          200: '#FFB8CF',
          300: '#FF8AB3',
          400: '#FF5C97',
          500: '#FF2E7B',
          600: '#E01A65',
          700: '#B8134F',
          800: '#8F0F3D',
          900: '#660A2C',
        },
        warm: {
          50: '#FFFAF5',
          100: '#FFF0E0',
          200: '#FFE0C2',
          300: '#FFCBA3',
          400: '#FFB080',
          500: '#FF9050',
          600: '#E07030',
          700: '#A85020',
          800: '#704018',
          900: '#3D2510',
        },
        text: {
          primary: '#2D2A3E',
          secondary: '#6B6580',
          light: '#9B95AD',
          muted: '#C5C0D3',
        },
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      boxShadow: {
        'soft': '0 2px 20px -5px rgba(255, 46, 123, 0.08)',
        'card': '0 4px 30px -8px rgba(45, 42, 62, 0.08)',
        'card-hover': '0 12px 40px -8px rgba(255, 46, 123, 0.15)',
        'glow-pink': '0 0 50px -12px rgba(255, 126, 179, 0.25)',
        'glow-mint': '0 0 50px -12px rgba(125, 211, 176, 0.25)',
        'cta': '0 6px 20px -4px rgba(255, 46, 123, 0.4)',
        'cta-hover': '0 10px 30px -4px rgba(255, 46, 123, 0.5)',
        'image': '0 8px 30px -6px rgba(45, 42, 62, 0.12)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 3s ease-in-out infinite',
        'wiggle': 'wiggle 2s ease-in-out infinite',
        'bounce-gentle': 'bounceGentle 2s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
        'slide-in': 'slideIn 0.8s ease-out forwards',
        'fade-up': 'fadeUp 0.6s ease-out forwards',
        'scale-in': 'scaleIn 0.5s ease-out forwards',
        'spin-slow': 'spin 15s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.8', transform: 'scale(1.02)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
